version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    depends_on:
      - 'db'
    build:
      context: .
      dockerfile: Dockerfile
    image: railscoolbean
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 80:3000
    volumes:
      - .:/app